In [37]:
fichero = open('datos.txt')
lista = []

arbolesvisibles = 0
for linea in fichero:
    lista.append(linea)
finalizado = False
linea = 0
nombre_listas = []
matriz = []

while not finalizado:
    try:
        locals()["linea" + str(linea)] = []
        nombre_listas.append("linea" + str(linea))
        for i in lista[linea]:
            if i != "\n":
                locals()["linea" + str(linea)].append(int(i))
        matriz.append(locals()["linea" + str(linea)])
        # for i in range(0, len(lista[linea])):
        #     for j in range(0, len(lista[linea][i])):
        #         if (max(lista[linea][i]) == lista[linea][i][j] and lista[linea].count(lista[linea][i][j] == 1)) or (max(lista[linea][:][j]) == lista[linea][i][j] and lista[linea].count(lista[linea][i][j] == 1)) or (max (lista[])):  
        #             arbolesvisibles += 1
        # print(lista[linea])
        linea+=1
    except:
        finalizado = True

# print(len(lista[0]))



In [38]:
matriz#Arboles visibles desde 4 lados


import numpy as np


matriz = np.array(matriz)
print(matriz)

for i in range(0, len(matriz)):
    locals()["columna" + str(i)] = matriz[:,i]
    locals()["fila" + str(i)] = matriz[i]


for i in range (0, len (matriz)):
    for j in range (0, len (matriz)):
        fila = i
        columna = j
        # Primero checamos a cual fija y columna pertenece y si esta fuera
        if fila == 0 or columna == 0 or fila == len(matriz) - 1 or columna == len(matriz) - 1:
            arbolesvisibles += 1
        else:

            if matriz[fila][columna] > max(matriz[fila][:columna]):
                arbolesvisibles += 1

            elif  matriz[fila][columna] > max(matriz[fila][columna + 1:]):
                arbolesvisibles += 1

            elif matriz[fila][columna] > max(locals()["columna" + str(columna)][:fila ]):
                arbolesvisibles += 1

            elif matriz[fila][columna] > max(locals()["columna" + str(columna)][fila + 1:]):
                arbolesvisibles += 1
print(arbolesvisibles)


[[0 2 1 ... 0 0 1]
 [2 1 2 ... 1 2 0]
 [0 0 1 ... 0 1 1]
 ...
 [0 0 1 ... 1 1 0]
 [2 1 0 ... 0 2 0]
 [0 0 1 ... 2 1 1]]
1809


In [45]:
puntuacion = []

for i in range (0, len (matriz)):
    for j in range (0, len (matriz)):
        fila = i
        columna = j
        # Vamos a ver cuantos arboles podemos llegar a ver
        right = 0
        left = 0
        up = 0
        down = 0
        if fila == 0 or columna == 0 or fila == len(matriz) - 1 or columna == len(matriz) - 1:
            puntuacion.append(0)
        else:
            print("Fila: ", fila, "Columna: ", columna)
            for k in range (columna + 1, len(matriz)):
                if matriz[fila][columna] > matriz[fila][k]:
                    right += 1
                if matriz[fila][columna] == matriz[fila][k] or matriz[fila][columna] < matriz[fila][k]:
                    right += 1
                    break
            for k in range (columna - 1, -1, -1):
                if matriz[fila][columna] > matriz[fila][k]:
                    left += 1
                if matriz[fila][columna] == matriz[fila][k] or matriz[fila][columna] < matriz[fila][k]:
                    left += 1
                    break
            for k in range (fila + 1, len(matriz)):
                if matriz[fila][columna] > matriz[k][columna]:
                    down += 1
                if matriz[fila][columna] == matriz[k][columna] or matriz[fila][columna] < matriz[k][columna]:
                    down += 1
                    break
            for k in range (fila - 1, -1, -1):
                if matriz[fila][columna] > matriz[k][columna]:
                    up += 1
                if matriz[fila][columna] == matriz[k][columna] or matriz[fila][columna] < matriz[k][columna]:
                    up += 1
                    break
            print("Right: ", right, "Left: ", left, "Up: ", up, "Down: ", down)
            print("Puntuacion: ", right * left * up * down)
            puntuacion.append( right * left * up * down)
            
print(max(puntuacion))

Fila:  1 Columna:  1
Right:  1 Left:  1 Up:  1 Down:  3
Puntuacion:  3
Fila:  1 Columna:  2
Right:  3 Left:  2 Up:  1 Down:  6
Puntuacion:  36
Fila:  1 Columna:  3
Right:  1 Left:  1 Up:  1 Down:  1
Puntuacion:  1
Fila:  1 Columna:  4
Right:  1 Left:  1 Up:  1 Down:  1
Puntuacion:  1
Fila:  1 Columna:  5
Right:  1 Left:  3 Up:  1 Down:  1
Puntuacion:  3
Fila:  1 Columna:  6
Right:  3 Left:  1 Up:  1 Down:  3
Puntuacion:  9
Fila:  1 Columna:  7
Right:  1 Left:  1 Up:  1 Down:  1
Puntuacion:  1
Fila:  1 Columna:  8
Right:  1 Left:  1 Up:  1 Down:  1
Puntuacion:  1
Fila:  1 Columna:  9
Right:  11 Left:  9 Up:  1 Down:  2
Puntuacion:  198
Fila:  1 Columna:  10
Right:  1 Left:  1 Up:  1 Down:  1
Puntuacion:  1
Fila:  1 Columna:  11
Right:  3 Left:  2 Up:  1 Down:  1
Puntuacion:  6
Fila:  1 Columna:  12
Right:  1 Left:  1 Up:  1 Down:  1
Puntuacion:  1
Fila:  1 Columna:  13
Right:  1 Left:  2 Up:  1 Down:  1
Puntuacion:  2
Fila:  1 Columna:  14
Right:  3 Left:  3 Up:  1 Down:  2
Puntuacion: 